import '../models/models.dart';
import 'db/finance_db.dart';

class MockData {
  static const bool isEnabled = true;

  static Student get student => Student(
        mssv: 'admin',
        hoTen: 'Nguyễn Văn A',
        ngaySinh: '01/01/2005',
        gioiTinh: 'Nam',
        chuyenNganh: 'Công nghệ thông tin',
        heDaoTao: 'Đại học chính quy',
        nienKhoa: '2023-2027',
        khoaHoc: 'K23',
        cmnd: '001002003004',
        email: 'admin@example.com',
        dienThoai: '0988123456',
        queQuan: 'Hà Nội',
        diaChiBaoTin: 'Đại học Kiến trúc Hà Nội',
        lastUpdated: DateTime.now(),
      );

  static List<LichHoc> getLichHoc() {
    final now = DateTime.now();
    // Start of current week (Monday)
    final monday = now.subtract(Duration(days: now.weekday - 1));
    final sunday = monday.add(const Duration(days: 6));

    final thoiGianStr =
        '${monday.day.toString().padLeft(2, '0')}/${monday.month.toString().padLeft(2, '0')}/${monday.year}'
        '-${sunday.day.toString().padLeft(2, '0')}/${sunday.month.toString().padLeft(2, '0')}/${sunday.year}';

    return [
      LichHoc(
        tenHocPhan: 'Lập trình Flutter',
        soTinChi: 3,
        tenLopTinChi: 'FLUTTER_K21',
        thoiGian: thoiGianStr,
        thu: 'Thứ 2',
        tiet: '1-3',
        phong: 'I.801',
        giaoVien: 'Lê Văn A',
        hocKy: 2,
        namHoc: '2024-2025',
        dotHoc: 1,
        chuyenNganh: 'CNTT',
      ),
      LichHoc(
        tenHocPhan: 'Kiến trúc máy tính',
        soTinChi: 3,
        tenLopTinChi: 'KTMT_K21',
        thoiGian: thoiGianStr,
        thu: 'Thứ 4',
        tiet: '4-6',
        phong: 'H.605',
        giaoVien: 'Trần Thị B',
        hocKy: 2,
        namHoc: '2024-2025',
        dotHoc: 1,
        chuyenNganh: 'CNTT',
      ),
      LichHoc(
        tenHocPhan: 'Trí tuệ nhân tạo',
        soTinChi: 3,
        tenLopTinChi: 'AI_K21',
        thoiGian: thoiGianStr,
        thu: 'Thứ 6',
        tiet: '7-9',
        phong: 'M.907',
        giaoVien: 'Nguyễn Văn C',
        hocKy: 2,
        namHoc: '2024-2025',
        dotHoc: 1,
        chuyenNganh: 'CNTT',
      ),
      LichHoc(
        tenHocPhan: 'Tiếng Anh P3',
        soTinChi: 2,
        tenLopTinChi: 'ENG3_K21',
        thoiGian: thoiGianStr,
        thu: 'Thứ 7',
        tiet: '10-12',
        phong: 'I.302',
        giaoVien: 'Phạm Thị D',
        hocKy: 2,
        namHoc: '2024-2025',
        dotHoc: 1,
        chuyenNganh: 'CNTT',
      ),
    ];
  }

  static DiemSummary getDiemSummary() => DiemSummary(
        tbcTichLuyHe4: 3.2,
        tbcTichLuyHe10: 8.1,
        tbcHocTapHe4: 3.2,
        tbcHocTapHe10: 8.1,
        xepLoaiHe4: 'Giỏi',
        xepLoaiHe10: 'Giỏi',
        soTinChiTichLuy: 56,
        soTinChiTichLuyMax: 56,
        soTinChiHocTap: 56,
        diemKhenThuong: 0.0,
      );

  static List<LichThi> getLichThi() {
    final now = DateTime.now();
    final tomorrow = now.add(const Duration(days: 1));
    final nextWeek = now.add(const Duration(days: 7));
    final nextMonth = now.add(const Duration(days: 30));

    String formatDate(DateTime d) =>
        '${d.day.toString().padLeft(2, '0')}/${d.month.toString().padLeft(2, '0')}/${d.year}';

    return [
      LichThi(
        tenMonHoc: 'Lập trình Flutter',
        soTinChi: 3,
        ngayThi: formatDate(tomorrow),
        caThi: 'Sáng',
        gioBatDau: '07:30',
        gioKetThuc: '09:30',
        sooBaoDanh: '105',
        phong: 'I.801',
        hinhThucThi: 'Thực hành',
        hocKy: 2,
        namHoc: '2024-2025',
      ),
      LichThi(
        tenMonHoc: 'Kiến trúc máy tính',
        soTinChi: 3,
        ngayThi: formatDate(nextWeek),
        caThi: 'Chiều',
        gioBatDau: '13:00',
        gioKetThuc: '15:00',
        sooBaoDanh: '082',
        phong: 'H.605',
        hinhThucThi: 'Thi viết',
        hocKy: 2,
        namHoc: '2024-2025',
      ),
      LichThi(
        tenMonHoc: 'Trí tuệ nhân tạo',
        soTinChi: 3,
        ngayThi: formatDate(nextMonth),
        caThi: 'Sáng',
        gioBatDau: '09:00',
        gioKetThuc: '11:00',
        sooBaoDanh: '199',
        phong: 'M.907',
        hinhThucThi: 'Vấn đáp',
        hocKy: 2,
        namHoc: '2024-2025',
      ),
    ];
  }

  static List<DiemMonHoc> getDiem() {
    return [
      // ===== HK1 2025-2026 (dữ liệu thực của bạn) =====
      DiemMonHoc(
          maMonHoc: 'CT4102',
          tenMonHoc: 'Pháp luật đại cương',
          soTinChi: 2,
          coefficient: 1,
          componentScore: '7 | 9',
          examScore: '7.8',
          avgGrade: 8.0,
          diemTongKet: 3,
          xepLoai: 'B',
          hocKy: 1,
          namHoc: '2025-2026'),
      DiemMonHoc(
          maMonHoc: 'TH4304',
          tenMonHoc: 'Kỹ thuật lập trình',
          soTinChi: 3,
          coefficient: 1,
          componentScore: '8 | 8.5',
          examScore: '8.0',
          avgGrade: 8.2,
          diemTongKet: 3,
          xepLoai: 'B',
          hocKy: 1,
          namHoc: '2025-2026'),
      DiemMonHoc(
          maMonHoc: 'CT4002',
          tenMonHoc: 'Lịch sử Đảng CSVN',
          soTinChi: 2,
          coefficient: 1,
          componentScore: '1 | 9',
          examScore: '7.0',
          avgGrade: 7.4,
          diemTongKet: 3,
          xepLoai: 'B',
          hocKy: 1,
          namHoc: '2025-2026'),
      DiemMonHoc(
          maMonHoc: 'TH4306',
          tenMonHoc: 'Công nghệ phần mềm',
          soTinChi: 3,
          coefficient: 1,
          componentScore: '9',
          examScore: '5.5',
          avgGrade: 6.9,
          diemTongKet: 2,
          xepLoai: 'C',
          hocKy: 1,
          namHoc: '2025-2026'),
      DiemMonHoc(
          maMonHoc: 'TH4320',
          tenMonHoc: 'Trí tuệ nhân tạo',
          soTinChi: 3,
          coefficient: 1,
          componentScore: '6.5',
          examScore: '5.5',
          avgGrade: 5.9,
          diemTongKet: 2,
          xepLoai: 'C',
          hocKy: 1,
          namHoc: '2025-2026'),
      DiemMonHoc(
          maMonHoc: 'TH5206',
          tenMonHoc: 'Mạng máy tính',
          soTinChi: 3,
          coefficient: 1,
          componentScore: '7',
          examScore: '6.5',
          avgGrade: 6.7,
          diemTongKet: 2,
          xepLoai: 'C',
          hocKy: 1,
          namHoc: '2025-2026'),
      DiemMonHoc(
          maMonHoc: 'TH5209',
          tenMonHoc: 'Xử lý ảnh',
          soTinChi: 3,
          coefficient: 1,
          componentScore: '6',
          examScore: '9.0',
          avgGrade: 7.8,
          diemTongKet: 3,
          xepLoai: 'B',
          hocKy: 1,
          namHoc: '2025-2026'),
      DiemMonHoc(
          maMonHoc: 'TH4316',
          tenMonHoc: 'Công nghệ Java',
          soTinChi: 3,
          coefficient: 1,
          componentScore: '8.5',
          examScore: '8.0',
          avgGrade: 8.2,
          diemTongKet: 3,
          xepLoai: 'B',
          hocKy: 1,
          namHoc: '2025-2026'),
      DiemMonHoc(
          maMonHoc: 'TH5208',
          tenMonHoc: 'Phân tích & TKHTTT',
          soTinChi: 3,
          coefficient: 1,
          componentScore: '8.5',
          examScore: '7.5',
          avgGrade: 7.9,
          diemTongKet: 3,
          xepLoai: 'B',
          hocKy: 1,
          namHoc: '2025-2026'),

      // ===== HK2 2025-2026 (mẫu — bạn thay số thực) =====
      DiemMonHoc(
          maMonHoc: 'TH5301',
          tenMonHoc: 'Lập trình .NET',
          soTinChi: 3,
          coefficient: 1,
          componentScore: '8',
          examScore: '7.5',
          avgGrade: 7.7,
          diemTongKet: 3,
          xepLoai: 'B',
          hocKy: 2,
          namHoc: '2025-2026'),
      DiemMonHoc(
          maMonHoc: 'TH5302',
          tenMonHoc: 'Kiểm thử phần mềm',
          soTinChi: 3,
          coefficient: 1,
          componentScore: '7',
          examScore: '6.5',
          avgGrade: 6.7,
          diemTongKet: 2,
          xepLoai: 'C',
          hocKy: 2,
          namHoc: '2025-2026'),
      DiemMonHoc(
          maMonHoc: 'TH5303',
          tenMonHoc: 'Đồ án tốt nghiệp',
          soTinChi: 5,
          coefficient: 1,
          componentScore: '9',
          examScore: '8.5',
          avgGrade: 8.7,
          diemTongKet: 4,
          xepLoai: 'A',
          hocKy: 2,
          namHoc: '2025-2026'),

      // ===== HK1 2024-2025 (mẫu) =====
      DiemMonHoc(
          maMonHoc: 'CT3001',
          tenMonHoc: 'Toán cao cấp A1',
          soTinChi: 4,
          coefficient: 1,
          componentScore: '6.5',
          examScore: '7.0',
          avgGrade: 6.8,
          diemTongKet: 2,
          xepLoai: 'C',
          hocKy: 1,
          namHoc: '2024-2025'),
      DiemMonHoc(
          maMonHoc: 'CT3002',
          tenMonHoc: 'Vật lý đại cương',
          soTinChi: 3,
          coefficient: 1,
          componentScore: '7',
          examScore: '7.5',
          avgGrade: 7.3,
          diemTongKet: 3,
          xepLoai: 'B',
          hocKy: 1,
          namHoc: '2024-2025'),
      DiemMonHoc(
          maMonHoc: 'TH3101',
          tenMonHoc: 'Lập trình cơ bản',
          soTinChi: 3,
          coefficient: 1,
          componentScore: '8',
          examScore: '8.5',
          avgGrade: 8.3,
          diemTongKet: 3,
          xepLoai: 'B',
          hocKy: 1,
          namHoc: '2024-2025'),

      // ===== HK2 2024-2025 (mẫu) =====
      DiemMonHoc(
          maMonHoc: 'CT3101',
          tenMonHoc: 'Toán cao cấp A2',
          soTinChi: 4,
          coefficient: 1,
          componentScore: '7',
          examScore: '6.5',
          avgGrade: 6.7,
          diemTongKet: 2,
          xepLoai: 'C',
          hocKy: 2,
          namHoc: '2024-2025'),
      DiemMonHoc(
          maMonHoc: 'TH3201',
          tenMonHoc: 'Cấu trúc dữ liệu',
          soTinChi: 3,
          coefficient: 1,
          componentScore: '8.5',
          examScore: '8.0',
          avgGrade: 8.2,
          diemTongKet: 3,
          xepLoai: 'B',
          hocKy: 2,
          namHoc: '2024-2025'),
      DiemMonHoc(
          maMonHoc: 'TH3202',
          tenMonHoc: 'Cơ sở dữ liệu',
          soTinChi: 3,
          coefficient: 1,
          componentScore: '9',
          examScore: '8.5',
          avgGrade: 8.7,
          diemTongKet: 4,
          xepLoai: 'A',
          hocKy: 2,
          namHoc: '2024-2025'),

      // ===== HK1 2023-2024 =====
      DiemMonHoc(
          maMonHoc: 'TC2611',
          tenMonHoc: 'Toán Đại số',
          soTinChi: 3,
          coefficient: 1,
          componentScore: '8',
          examScore: '7.5',
          avgGrade: 7.7,
          diemTongKet: 3,
          xepLoai: 'B',
          hocKy: 1,
          namHoc: '2023-2024'),
      DiemMonHoc(
          maMonHoc: 'CT3901.1',
          tenMonHoc: 'Triết học Mác - LêNin',
          soTinChi: 3,
          coefficient: 1,
          componentScore: '7',
          examScore: '8.0',
          avgGrade: 7.6,
          diemTongKet: 3,
          xepLoai: 'B',
          hocKy: 1,
          namHoc: '2023-2024'),
      DiemMonHoc(
          maMonHoc: 'TC2701',
          tenMonHoc: 'Vật lý P1',
          soTinChi: 2,
          coefficient: 1,
          componentScore: '6',
          examScore: '6.5',
          avgGrade: 6.3,
          diemTongKet: 2,
          xepLoai: 'C',
          hocKy: 1,
          namHoc: '2023-2024'),

      // ===== HK2 2023-2024 =====
      DiemMonHoc(
          maMonHoc: 'CT3902.1',
          tenMonHoc: 'Kinh tế chính trị Mác - Lênin',
          soTinChi: 2,
          coefficient: 1,
          componentScore: '9',
          examScore: '8.0',
          avgGrade: 8.4,
          diemTongKet: 3,
          xepLoai: 'B',
          hocKy: 2,
          namHoc: '2023-2024'),
      DiemMonHoc(
          maMonHoc: 'TC2612',
          tenMonHoc: 'Giải tích 1',
          soTinChi: 3,
          coefficient: 1,
          componentScore: '7.5',
          examScore: '7.0',
          avgGrade: 7.2,
          diemTongKet: 3,
          xepLoai: 'B',
          hocKy: 2,
          namHoc: '2023-2024'),

      // ===== HK2 2022-2023 =====
      DiemMonHoc(
          maMonHoc: 'TC2610',
          tenMonHoc: 'Toán cao cấp 1',
          soTinChi: 3,
          coefficient: 1,
          componentScore: '6.5',
          examScore: '7.0',
          avgGrade: 6.8,
          diemTongKet: 2,
          xepLoai: 'C',
          hocKy: 2,
          namHoc: '2022-2023'),
      DiemMonHoc(
          maMonHoc: 'TH3101',
          tenMonHoc: 'Tin học đại cương',
          soTinChi: 2,
          coefficient: 1,
          componentScore: '8.5',
          examScore: '9.0',
          avgGrade: 8.8,
          diemTongKet: 4,
          xepLoai: 'A',
          hocKy: 2,
          namHoc: '2022-2023'),
    ];
  }

  static List<DiemMonHoc> getDiemOverview() {
    return getDiem().map((d) {
      return DiemMonHoc(
        maMonHoc: d.maMonHoc,
        tenMonHoc: d.tenMonHoc,
        soTinChi: d.soTinChi,
        coefficient: d.coefficient,
        componentScore: d.componentScore,
        examScore: d.examScore,
        avgGrade: d.avgGrade,
        diemTongKet: d.diemTongKet,
        xepLoai: d.xepLoai,
        hocKy: 0,
        namHoc: 'Overview',
        rawAvgGrade: d.rawAvgGrade,
        rawDiemSo: d.rawDiemSo,
        rawXepLoai: d.rawXepLoai,
        rawComponentScore: d.rawComponentScore,
        rawExamScore: d.rawExamScore,
        lastUpdated: d.lastUpdated,
      );
    }).toList();
  }

  static Future<void> populateFinance() async {
    // ===== FEE SUMMARY =====
    await FinanceDb.saveFeeSummary({
      'nam_hoc': '2023-2024',
      'hoc_ky': 1,
      'muc_hoc_phi': 2358000.0,
      'mien_giam': 0.0,
      'phai_nop': 2358000.0,
      'da_nop': 2358000.0,
      'thua_thieu': 0.0,
    });
    await FinanceDb.saveFeeSummary({
      'nam_hoc': '2023-2024',
      'hoc_ky': 2,
      'muc_hoc_phi': 2365000.0,
      'mien_giam': 0.0,
      'phai_nop': 2365000.0,
      'da_nop': 2365000.0,
      'thua_thieu': 0.0,
    });
    await FinanceDb.saveFeeSummary({
      'nam_hoc': '2024-2025',
      'hoc_ky': 1,
      'muc_hoc_phi': 1254000.0,
      'mien_giam': 0.0,
      'phai_nop': 1254000.0,
      'da_nop': 1254000.0,
      'thua_thieu': 0.0,
    });
    await FinanceDb.saveFeeSummary({
      'nam_hoc': '2024-2025',
      'hoc_ky': 2,
      'muc_hoc_phi': 3256000.0,
      'mien_giam': 0.0,
      'phai_nop': 3256000.0,
      'da_nop': 3256000.0,
      'thua_thieu': 0.0,
    });
    await FinanceDb.saveFeeSummary({
      'nam_hoc': '2025-2026',
      'hoc_ky': 1,
      'muc_hoc_phi': 15500000.0,
      'mien_giam': 0.0,
      'phai_nop': 15500000.0,
      'da_nop': 15500000.0,
      'thua_thieu': 0.0,
    });
    await FinanceDb.saveFeeSummary({
      'nam_hoc': '2025-2026',
      'hoc_ky': 2,
      'muc_hoc_phi': 10000000.0,
      'mien_giam': 0.0,
      'phai_nop': 10000000.0,
      'da_nop': 10000000.0,
      'thua_thieu': 0.0,
    });

    // ===== PAYMENT RECEIPTS =====
    await FinanceDb.savePaymentReceipts([
      {
        'so_phieu': '15743',
        'nam_hoc': '2023-2024',
        'hoc_ky': 1,
        'lan_thu': 1,
        'dot_thu': 1,
        'ngay_thu': '09/09/2023',
        'tong_tien_phieu': 2358000.0,
        'trang_thai': 'Đã nộp',
        'last_updated': DateTime.now().toIso8601String(),
      },
      {
        'so_phieu': '35759',
        'nam_hoc': '2023-2024',
        'hoc_ky': 2,
        'lan_thu': 1,
        'dot_thu': 1,
        'ngay_thu': '03/02/2024',
        'tong_tien_phieu': 2365000.0,
        'trang_thai': 'Đã nộp',
        'last_updated': DateTime.now().toIso8601String(),
      },
      {
        'so_phieu': '15546',
        'nam_hoc': '2024-2025',
        'hoc_ky': 1,
        'lan_thu': 1,
        'dot_thu': 1,
        'ngay_thu': '10/07/2024',
        'tong_tien_phieu': 1254000.0,
        'trang_thai': 'Đã nộp',
        'last_updated': DateTime.now().toIso8601String(),
      },
      {
        'so_phieu': '31396',
        'nam_hoc': '2024-2025',
        'hoc_ky': 2,
        'lan_thu': 1,
        'dot_thu': 1,
        'ngay_thu': '13/02/2025',
        'tong_tien_phieu': 3256000.0,
        'trang_thai': 'Đã nộp',
        'last_updated': DateTime.now().toIso8601String(),
      },
      {
        'so_phieu': '9207',
        'nam_hoc': '2025-2026',
        'hoc_ky': 1,
        'lan_thu': 1,
        'dot_thu': 1,
        'ngay_thu': '15/09/2025',
        'tong_tien_phieu': 15500000.0,
        'trang_thai': 'Đã nộp',
        'last_updated': DateTime.now().toIso8601String(),
      },
      {
        'so_phieu': '26944',
        'nam_hoc': '2025-2026',
        'hoc_ky': 2,
        'lan_thu': 1,
        'dot_thu': 1,
        'ngay_thu': '24/02/2026',
        'tong_tien_phieu': 10000000.0,
        'trang_thai': 'Đã nộp',
        'last_updated': DateTime.now().toIso8601String(),
      },
    ]);

    // ===== FEE DETAILS =====
    await FinanceDb.saveFeeDetails([
      // --- Phiếu 15743 | HK1 2023-2024 ---
      {
        'so_phieu': '15743',
        'nam_hoc': '2023-2024',
        'hoc_ky': 1,
        'ten_hoc_phan': 'Giáo dục quốc phòng',
        'loai_khoan': 'Học phí',
        'so_tien_phai_nop': 3411200.0,
        'so_tien_mien_giam': 0.0,
        'so_tien_da_nop': 3411200.0,
        'so_tien_thua_thieu': 0.0,
        'trang_thai': 'Đã nộp',
        'ngay_nop': '09/09/2023',
      },
      {
        'so_phieu': '15743',
        'nam_hoc': '2023-2024',
        'hoc_ky': 1,
        'ten_hoc_phan': 'Triết học Mác - LêNin',
        'loai_khoan': 'Học phí',
        'so_tien_phai_nop': 1279200.0,
        'so_tien_mien_giam': 0.0,
        'so_tien_da_nop': 1279200.0,
        'so_tien_thua_thieu': 0.0,
        'trang_thai': 'Đã nộp',
        'ngay_nop': '09/09/2023',
      },
      {
        'so_phieu': '15743',
        'nam_hoc': '2023-2024',
        'hoc_ky': 1,
        'ten_hoc_phan': 'Toán Đại số',
        'loai_khoan': 'Học phí',
        'so_tien_phai_nop': 1279200.0,
        'so_tien_mien_giam': 0.0,
        'so_tien_da_nop': 1279200.0,
        'so_tien_thua_thieu': 0.0,
        'trang_thai': 'Đã nộp',
        'ngay_nop': '09/09/2023',
      },
      {
        'so_phieu': '15743',
        'nam_hoc': '2023-2024',
        'hoc_ky': 1,
        'ten_hoc_phan': 'Vật lý P1',
        'loai_khoan': 'Học phí',
        'so_tien_phai_nop': 852800.0,
        'so_tien_mien_giam': 0.0,
        'so_tien_da_nop': 852800.0,
        'so_tien_thua_thieu': 0.0,
        'trang_thai': 'Đã nộp',
        'ngay_nop': '09/09/2023',
      },
      // // Các môn còn lại của HK1 2023-2024 (tổng = 7.248.800)
      // {
      //   'so_phieu': '15743',
      //   'nam_hoc': '2023-2024',
      //   'hoc_ky': 1,
      //   'ten_hoc_phan': 'Các môn còn lại HK1',
      //   'loai_khoan': 'Học phí',
      //   'so_tien_phai_nop': 426400.0,
      //   'so_tien_mien_giam': 0.0,
      //   'so_tien_da_nop': 426400.0,
      //   'so_tien_thua_thieu': 0.0,
      //   'trang_thai': 'Đã nộp',
      //   'ngay_nop': '09/09/2023',
      // },

      // --- Phiếu 35759 | HK2 2023-2024 ---
      {
        'so_phieu': '35759',
        'nam_hoc': '2023-2024',
        'hoc_ky': 2,
        'ten_hoc_phan': 'Học phí HK2 2023-2024',
        'loai_khoan': 'Học phí',
        'so_tien_phai_nop': 6822400.0,
        'so_tien_mien_giam': 0.0,
        'so_tien_da_nop': 6822400.0,
        'so_tien_thua_thieu': 0.0,
        'trang_thai': 'Đã nộp',
        'ngay_nop': '03/02/2024',
      },

      // --- Phiếu 15546 | HK1 2024-2025 ---
      {
        'so_phieu': '15546',
        'nam_hoc': '2024-2025',
        'hoc_ky': 1,
        'ten_hoc_phan': 'Học phí HK1 2024-2025',
        'loai_khoan': 'Học phí',
        'so_tien_phai_nop': 8199100.0,
        'so_tien_mien_giam': 0.0,
        'so_tien_da_nop': 8199100.0,
        'so_tien_thua_thieu': 0.0,
        'trang_thai': 'Đã nộp',
        'ngay_nop': '10/07/2024',
      },

      // --- Phiếu 31396 | HK2 2024-2025 ---
      {
        'so_phieu': '31396',
        'nam_hoc': '2024-2025',
        'hoc_ky': 2,
        'ten_hoc_phan': 'Học phí HK2 2024-2025',
        'loai_khoan': 'Học phí',
        'so_tien_phai_nop': 9163700.0,
        'so_tien_mien_giam': 0.0,
        'so_tien_da_nop': 9163700.0,
        'so_tien_thua_thieu': 0.0,
        'trang_thai': 'Đã nộp',
        'ngay_nop': '13/02/2025',
      },

      // --- Phiếu 9207 | HK1 2025-2026 ---
      {
        'so_phieu': '9207',
        'nam_hoc': '2025-2026',
        'hoc_ky': 1,
        'ten_hoc_phan': 'Học phí HK1 2025-2026',
        'loai_khoan': 'Học phí',
        'so_tien_phai_nop': 13600000.0,
        'so_tien_mien_giam': 0.0,
        'so_tien_da_nop': 13600000.0,
        'so_tien_thua_thieu': 0.0,
        'trang_thai': 'Đã nộp',
        'ngay_nop': '15/09/2025',
      },

      // --- Phiếu 26944 | HK2 2025-2026 ---
      {
        'so_phieu': '26944',
        'nam_hoc': '2025-2026',
        'hoc_ky': 2,
        'ten_hoc_phan': 'Học phí HK2 2025-2026',
        'loai_khoan': 'Học phí',
        'so_tien_phai_nop': 9792000.0,
        'so_tien_mien_giam': 0.0,
        'so_tien_da_nop': 9792000.0,
        'so_tien_thua_thieu': 0.0,
        'trang_thai': 'Đã nộp',
        'ngay_nop': '24/02/2026',
      },
    ]);
  }

  static List<Map<String, String>> getChuyenNganhChinh() {
    return [
      // ── KỲ 0 (Học liệu dùng chung) ──────────────────────────
      {
        'khoi': '',
        'ky': '0',
        'ma': 'HocLieu_Di',
        'ten': 'Học liệu dịch vụ và thư viện',
        'elearning': '0',
        'tu_chon': '0',
        'tin_chi': '1.2',
        'tong_tiet': '0',
      },

      // ── KỲ 1 ────────────────────────────────────────────────
      {
        'khoi': 'Khối kiến thức đại cương',
        'ky': '1',
        'ma': 'QP6001',
        'ten': 'Giáo dục quốc phòng',
        'elearning': '0',
        'tu_chon': '0',
        'tin_chi': '8',
        'tong_tiet': '240',
      },
      {
        'khoi': 'Khối kiến thức đại cương',
        'ky': '1',
        'ma': 'GD4501',
        'ten': 'Giáo dục thể chất P1',
        'elearning': '0',
        'tu_chon': '0',
        'tin_chi': '1',
        'tong_tiet': '30',
      },
      {
        'khoi': 'Khối kiến thức đại cương',
        'ky': '1',
        'ma': 'TC2611',
        'ten': 'Toán Đại số',
        'elearning': '0',
        'tu_chon': '0',
        'tin_chi': '3',
        'tong_tiet': '45',
      },
      {
        'khoi': 'Khối kiến thức đại cương',
        'ky': '1',
        'ma': 'CT3901.1',
        'ten': 'Triết học Mác - LêNin',
        'elearning': '0',
        'tu_chon': '0',
        'tin_chi': '3',
        'tong_tiet': '58',
      },
      {
        'khoi': 'Khối kiến thức đại cương',
        'ky': '1',
        'ma': 'TC2701',
        'ten': 'Vật lý P1',
        'elearning': '0',
        'tu_chon': '0',
        'tin_chi': '2',
        'tong_tiet': '30',
      },

      // ── KỲ 2 ────────────────────────────────────────────────
      {
        'khoi': 'Khối kiến thức đại cương',
        'ky': '2',
        'ma': 'GD4502',
        'ten': 'Giáo dục thể chất P2',
        'elearning': '0',
        'tu_chon': '0',
        'tin_chi': '1',
        'tong_tiet': '30',
      },
      {
        'khoi': 'Khối kiến thức đại cương',
        'ky': '2',
        'ma': 'CT3902.1',
        'ten': 'Kinh tế chính trị Mác - Lênin',
        'elearning': '0',
        'tu_chon': '0',
        'tin_chi': '2',
        'tong_tiet': '39',
      },
      {
        'khoi': 'Khối kiến thức đại cương',
        'ky': '2',
        'ma': 'TH5224',
        'ten': 'Kỹ năng thuyết trình',
        'elearning': '0',
        'tu_chon': '0',
        'tin_chi': '1',
        'tong_tiet': '15',
      },
      {
        'khoi': 'Khối kiến thức đại cương',
        'ky': '2',
        'ma': 'NN3700.1',
        'ten': 'Tiếng Anh tăng cường P1',
        'elearning': '1',
        'tu_chon': '1',
        'tin_chi': '3',
        'tong_tiet': '45',
      },
      {
        'khoi': 'Khối kiến thức đại cương',
        'ky': '2',
        'ma': 'NN3700.2',
        'ten': 'Tiếng Anh tăng cường P2',
        'elearning': '1',
        'tu_chon': '1',
        'tin_chi': '3',
        'tong_tiet': '45',
      },
      {
        'khoi': 'Khối kiến thức đại cương',
        'ky': '2',
        'ma': 'NN3800.1',
        'ten': 'Tiếng Pháp tăng cường P1',
        'elearning': '1',
        'tu_chon': '1',
        'tin_chi': '3',
        'tong_tiet': '45',
      },
      {
        'khoi': 'Khối kiến thức đại cương',
        'ky': '2',
        'ma': 'NN3800.2',
        'ten': 'Tiếng Pháp tăng cường P2',
        'elearning': '1',
        'tu_chon': '1',
        'tin_chi': '3',
        'tong_tiet': '45',
      },
      {
        'khoi': 'Khối kiến thức đại cương',
        'ky': '2',
        'ma': 'TH4301',
        'ten': 'Tin học đại cương',
        'elearning': '0',
        'tu_chon': '0',
        'tin_chi': '2',
        'tong_tiet': '45',
      },
      {
        'khoi': 'Khối kiến thức đại cương',
        'ky': '2',
        'ma': 'TC2612',
        'ten': 'Toán Giải tích',
        'elearning': '0',
        'tu_chon': '0',
        'tin_chi': '3',
        'tong_tiet': '45',
      },
      {
        'khoi': 'Khối kiến thức đại cương',
        'ky': '2',
        'ma': 'TC2702',
        'ten': 'Vật lý P2',
        'elearning': '0',
        'tu_chon': '0',
        'tin_chi': '2',
        'tong_tiet': '30',
      },

      // ── KỲ 3 ────────────────────────────────────────────────
      {
        'khoi': 'Khối kiến thức cơ sở ngành',
        'ky': '3',
        'ma': 'CT3903.1',
        'ten': 'Chủ nghĩa xã hội khoa học',
        'elearning': '0',
        'tu_chon': '0',
        'tin_chi': '2',
        'tong_tiet': '39',
      },
      {
        'khoi': 'Khối kiến thức cơ sở ngành',
        'ky': '3',
        'ma': 'CT4002',
        'ten': 'Lịch sử Đảng Cộng sản Việt Nam',
        'elearning': '0',
        'tu_chon': '0',
        'tin_chi': '2',
        'tong_tiet': '39',
      },
      {
        'khoi': 'Khối kiến thức cơ sở ngành',
        'ky': '3',
        'ma': 'TC2613',
        'ten': 'Toán rời rạc',
        'elearning': '0',
        'tu_chon': '0',
        'tin_chi': '3',
        'tong_tiet': '45',
      },
      {
        'khoi': 'Khối kiến thức cơ sở ngành',
        'ky': '3',
        'ma': 'TH4302',
        'ten': 'Lập trình hướng đối tượng',
        'elearning': '0',
        'tu_chon': '0',
        'tin_chi': '3',
        'tong_tiet': '60',
      },
      {
        'khoi': 'Khối kiến thức cơ sở ngành',
        'ky': '3',
        'ma': 'TH4303',
        'ten': 'Cơ sở dữ liệu',
        'elearning': '0',
        'tu_chon': '0',
        'tin_chi': '3',
        'tong_tiet': '60',
      },
      {
        'khoi': 'Khối kiến thức cơ sở ngành',
        'ky': '3',
        'ma': 'TH4304',
        'ten': 'Kỹ thuật lập trình',
        'elearning': '0',
        'tu_chon': '0',
        'tin_chi': '3',
        'tong_tiet': '60',
      },
      {
        'khoi': 'Khối kiến thức cơ sở ngành',
        'ky': '3',
        'ma': 'NN3701',
        'ten': 'Tiếng Anh P1',
        'elearning': '0',
        'tu_chon': '0',
        'tin_chi': '3',
        'tong_tiet': '45',
      },

      // ── KỲ 4 ────────────────────────────────────────────────
      {
        'khoi': 'Khối kiến thức cơ sở ngành',
        'ky': '4',
        'ma': 'CT4102',
        'ten': 'Pháp luật đại cương',
        'elearning': '0',
        'tu_chon': '0',
        'tin_chi': '2',
        'tong_tiet': '39',
      },
      {
        'khoi': 'Khối kiến thức cơ sở ngành',
        'ky': '4',
        'ma': 'TH4305',
        'ten': 'Cấu trúc dữ liệu và giải thuật',
        'elearning': '0',
        'tu_chon': '0',
        'tin_chi': '3',
        'tong_tiet': '60',
      },
      {
        'khoi': 'Khối kiến thức cơ sở ngành',
        'ky': '4',
        'ma': 'TH4306',
        'ten': 'Công nghệ phần mềm',
        'elearning': '0',
        'tu_chon': '0',
        'tin_chi': '3',
        'tong_tiet': '60',
      },
      {
        'khoi': 'Khối kiến thức cơ sở ngành',
        'ky': '4',
        'ma': 'TH5201',
        'ten': 'Kiến trúc máy tính',
        'elearning': '0',
        'tu_chon': '0',
        'tin_chi': '3',
        'tong_tiet': '45',
      },
      {
        'khoi': 'Khối kiến thức cơ sở ngành',
        'ky': '4',
        'ma': 'NN3702',
        'ten': 'Tiếng Anh P2',
        'elearning': '0',
        'tu_chon': '0',
        'tin_chi': '3',
        'tong_tiet': '45',
      },
      {
        'khoi': 'Khối kiến thức cơ sở ngành',
        'ky': '4',
        'ma': 'TH4307',
        'ten': 'Hệ điều hành',
        'elearning': '0',
        'tu_chon': '0',
        'tin_chi': '3',
        'tong_tiet': '45',
      },

      // ── KỲ 5 ────────────────────────────────────────────────
      {
        'khoi': 'Khối kiến thức chuyên ngành',
        'ky': '5',
        'ma': 'TH5202',
        'ten': 'Hệ thống thông tin quản lý',
        'elearning': '0',
        'tu_chon': '0',
        'tin_chi': '3',
        'tong_tiet': '45',
      },
      {
        'khoi': 'Khối kiến thức chuyên ngành',
        'ky': '5',
        'ma': 'TH5203',
        'ten': 'Lập trình Web',
        'elearning': '0',
        'tu_chon': '0',
        'tin_chi': '3',
        'tong_tiet': '60',
      },
      {
        'khoi': 'Khối kiến thức chuyên ngành',
        'ky': '5',
        'ma': 'TH5204',
        'ten': 'An toàn thông tin',
        'elearning': '0',
        'tu_chon': '0',
        'tin_chi': '3',
        'tong_tiet': '45',
      },
      {
        'khoi': 'Khối kiến thức chuyên ngành',
        'ky': '5',
        'ma': 'TH5205',
        'ten': 'Lập trình di động',
        'elearning': '0',
        'tu_chon': '0',
        'tin_chi': '3',
        'tong_tiet': '60',
      },
      {
        'khoi': 'Khối kiến thức chuyên ngành',
        'ky': '5',
        'ma': 'TH5206',
        'ten': 'Mạng máy tính',
        'elearning': '0',
        'tu_chon': '0',
        'tin_chi': '3',
        'tong_tiet': '45',
      },
      {
        'khoi': 'Khối kiến thức chuyên ngành',
        'ky': '5',
        'ma': 'NN3703',
        'ten': 'Tiếng Anh P3',
        'elearning': '0',
        'tu_chon': '0',
        'tin_chi': '2',
        'tong_tiet': '30',
      },

      // ── KỲ 6 ────────────────────────────────────────────────
      {
        'khoi': 'Khối kiến thức chuyên ngành',
        'ky': '6',
        'ma': 'TH5207',
        'ten': 'Học máy',
        'elearning': '0',
        'tu_chon': '0',
        'tin_chi': '3',
        'tong_tiet': '45',
      },
      {
        'khoi': 'Khối kiến thức chuyên ngành',
        'ky': '6',
        'ma': 'TH5208',
        'ten': 'Phân tích và thiết kế hệ thống thông tin',
        'elearning': '0',
        'tu_chon': '0',
        'tin_chi': '3',
        'tong_tiet': '45',
      },
      {
        'khoi': 'Khối kiến thức chuyên ngành',
        'ky': '6',
        'ma': 'TH5209',
        'ten': 'Xử lý ảnh',
        'elearning': '0',
        'tu_chon': '0',
        'tin_chi': '3',
        'tong_tiet': '45',
      },
      {
        'khoi': 'Khối kiến thức chuyên ngành',
        'ky': '6',
        'ma': 'TH4316',
        'ten': 'Công nghệ Java',
        'elearning': '0',
        'tu_chon': '0',
        'tin_chi': '3',
        'tong_tiet': '60',
      },
      {
        'khoi': 'Khối kiến thức chuyên ngành',
        'ky': '6',
        'ma': 'TH4320',
        'ten': 'Trí tuệ nhân tạo',
        'elearning': '0',
        'tu_chon': '0',
        'tin_chi': '3',
        'tong_tiet': '45',
      },
      {
        'khoi': 'Khối kiến thức chuyên ngành',
        'ky': '6',
        'ma': 'TH5210',
        'ten': 'Kiểm thử phần mềm',
        'elearning': '0',
        'tu_chon': '0',
        'tin_chi': '3',
        'tong_tiet': '45',
      },

      // ── KỲ 7 ────────────────────────────────────────────────
      {
        'khoi': 'Khối kiến thức chuyên ngành',
        'ky': '7',
        'ma': 'TH5301',
        'ten': 'Lập trình .NET',
        'elearning': '0',
        'tu_chon': '0',
        'tin_chi': '3',
        'tong_tiet': '60',
      },
      {
        'khoi': 'Khối kiến thức chuyên ngành',
        'ky': '7',
        'ma': 'TH5302',
        'ten': 'Điện toán đám mây',
        'elearning': '0',
        'tu_chon': '0',
        'tin_chi': '3',
        'tong_tiet': '45',
      },
      {
        'khoi': 'Khối kiến thức chuyên ngành',
        'ky': '7',
        'ma': 'TH5303',
        'ten': 'Phát triển ứng dụng đa nền tảng',
        'elearning': '0',
        'tu_chon': '0',
        'tin_chi': '3',
        'tong_tiet': '60',
      },
      {
        'khoi': 'Khối kiến thức chuyên ngành',
        'ky': '7',
        'ma': 'TH5304',
        'ten': 'Quản trị dự án phần mềm',
        'elearning': '0',
        'tu_chon': '0',
        'tin_chi': '2',
        'tong_tiet': '30',
      },
      {
        'khoi': 'Khối kiến thức chuyên ngành',
        'ky': '7',
        'ma': 'TH5305',
        'ten': 'Thực tập doanh nghiệp',
        'elearning': '0',
        'tu_chon': '0',
        'tin_chi': '3',
        'tong_tiet': '0',
      },

      // ── KỲ 8 ────────────────────────────────────────────────
      {
        'khoi': 'Khối kiến thức chuyên ngành',
        'ky': '8',
        'ma': 'TH5306',
        'ten': 'Xây dựng và triển khai phần mềm (DevOps)',
        'elearning': '0',
        'tu_chon': '0',
        'tin_chi': '3',
        'tong_tiet': '45',
      },
      {
        'khoi': 'Khối kiến thức chuyên ngành',
        'ky': '8',
        'ma': 'TH5307',
        'ten': 'Phân tích dữ liệu lớn',
        'elearning': '0',
        'tu_chon': '1',
        'tin_chi': '3',
        'tong_tiet': '45',
      },
      {
        'khoi': 'Khối kiến thức chuyên ngành',
        'ky': '8',
        'ma': 'TH5308',
        'ten': 'Thị giác máy tính',
        'elearning': '0',
        'tu_chon': '1',
        'tin_chi': '3',
        'tong_tiet': '45',
      },
      {
        'khoi': 'Khối kiến thức chuyên ngành',
        'ky': '8',
        'ma': 'TH5309',
        'ten': 'Hệ thống nhúng',
        'elearning': '0',
        'tu_chon': '1',
        'tin_chi': '3',
        'tong_tiet': '45',
      },
      {
        'khoi': 'Khối kiến thức chuyên ngành',
        'ky': '8',
        'ma': 'TH5310',
        'ten': 'Seminar tốt nghiệp',
        'elearning': '0',
        'tu_chon': '0',
        'tin_chi': '2',
        'tong_tiet': '30',
      },

      // ── KỲ 9 ────────────────────────────────────────────────
      {
        'khoi': 'Khối kiến thức chuyên ngành',
        'ky': '9',
        'ma': 'TH6001',
        'ten': 'Đồ án tốt nghiệp',
        'elearning': '0',
        'tu_chon': '0',
        'tin_chi': '10',
        'tong_tiet': '0',
      },
    ];
  }
}
